version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres
    env_file:
      - ./.env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5488:5432'
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   pgdata: