version: '3.8'

services:
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
      # Убираем монтирование node_modules для решения проблемы с bcrypt
      # - ./node_modules:/app/node_modules
    depends_on:
      dev-db:
        condition: service_healthy
    networks:
      - dev-app-network
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=dev-db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=cleanhouse_dev
      - JWT_SECRET=your-super-secret-jwt-key-for-development
      - JWT_REFRESH_SECRET=your-super-secret-refresh-jwt-key-for-development
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d
      - PORT=4000
      - WAHA_API_URL=https://cleanhouse123-waha-server-6ff4.twc1.net
      - WAHA_API_TOKEN=sha512:d4273065fd5d79963463cae272d31277c88b5c510c23460c5c31d72ea95705008bcb4ba25fb229d3e516714bbef2b902df03d43695f33a88f973664763677ca3
      - YOOKASSA_SHOP_ID=1193587
      - YOOKASSA_SECRET_KEY=test_qXKh3h-nMuuiZuKqowskhCczKnwEDCxlkix8Eo1wEJQ
      - BASE_URL=http://localhost:4000
      - FRONTEND_URL=http://localhost:5173
    restart: unless-stopped
  dev-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleanhouse_dev
    ports:
      - '5432:5432'
    volumes:
      - pg_dev_data:/var/lib/postgresql/data
    networks:
      - dev-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cleanhouse_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  dev-app-network:
    driver: bridge

volumes:
  pg_dev_data:
