version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres
    env_file:
      - ./.env.production
    ports:
      - '5488:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  waha:
    image: devlikeapro/waha
    platform: linux/amd64
    ports:
      - '3001:3000'
    volumes:
      - waha_sessions:/app/.sessions
    environment:
      - WAHA_API_URL=http://localhost:3000
      - WAHA_API_KEY=sha512:d4273065fd5d79963463cae272d31277c88b5c510c23460c5c31d72ea95705008bcb4ba25fb229d3e516714bbef2b902df03d43695f33a88f973664763677ca3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  waha_sessions: